# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fantasy.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("color rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("color rgb(255, 255, 255)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.batsman = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.batsman.setMinimumSize(QtCore.QSize(0, 10))
        self.batsman.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.batsman.setFont(font)
        self.batsman.setReadOnly(True)
        self.batsman.setObjectName("batsman")
        self.horizontalLayout_2.addWidget(self.batsman)
        self.bowler = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.bowler.setMinimumSize(QtCore.QSize(0, 12))
        self.bowler.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.bowler.setFont(font)
        self.bowler.setReadOnly(True)
        self.bowler.setObjectName("bowler")
        self.horizontalLayout_2.addWidget(self.bowler)
        self.allrounder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.allrounder.setMinimumSize(QtCore.QSize(0, 10))
        self.allrounder.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.allrounder.setFont(font)
        self.allrounder.setReadOnly(True)
        self.allrounder.setObjectName("allrounder")
        self.horizontalLayout_2.addWidget(self.allrounder)
        self.wicketkeeper = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.wicketkeeper.setMinimumSize(QtCore.QSize(0, 10))
        self.wicketkeeper.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.wicketkeeper.setFont(font)
        self.wicketkeeper.setReadOnly(True)
        self.wicketkeeper.setObjectName("wicketkeeper")
        self.horizontalLayout_2.addWidget(self.wicketkeeper)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pointavailable = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pointavailable.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pointavailable.setObjectName("pointavailable")
        self.horizontalLayout_5.addWidget(self.pointavailable)
        self.pointused = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pointused.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pointused.setObjectName("pointused")
        self.horizontalLayout_5.addWidget(self.pointused)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio_bat = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_bat.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.radio_bat.setFont(font)
        self.radio_bat.setObjectName("radio_bat")
        self.horizontalLayout_3.addWidget(self.radio_bat)
        self.radio_bow = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_bow.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.radio_bow.setFont(font)
        self.radio_bow.setObjectName("radio_bow")
        self.horizontalLayout_3.addWidget(self.radio_bow)
        self.radio_ar = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_ar.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.radio_ar.setFont(font)
        self.radio_ar.setObjectName("radio_ar")
        self.horizontalLayout_3.addWidget(self.radio_ar)
        self.radio_wk = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_wk.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.radio_wk.setFont(font)
        self.radio_wk.setObjectName("radio_wk")
        self.horizontalLayout_3.addWidget(self.radio_wk)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.available_player = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.available_player.setFont(font)
        self.available_player.setObjectName("available_player")
        self.verticalLayout.addWidget(self.available_player)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.teamname = QtWidgets.QLabel(self.centralwidget)
        self.teamname.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.teamname.setFont(font)
        self.teamname.setObjectName("teamname")
        self.verticalLayout_2.addWidget(self.teamname)
        self.selected_player = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.selected_player.setFont(font)
        self.selected_player.setObjectName("selected_player")
        self.verticalLayout_2.addWidget(self.selected_player)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Manage_Team = QtWidgets.QMenuBar(MainWindow)
        self.Manage_Team.setGeometry(QtCore.QRect(0, 0, 800, 25))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Manage_Team.setFont(font)
        self.Manage_Team.setAutoFillBackground(False)
        self.Manage_Team.setStyleSheet("background-color: rgb(177, 177, 177);")
        self.Manage_Team.setObjectName("Manage_Team")
        self.menuManages_Teams = QtWidgets.QMenu(self.Manage_Team)
        self.menuManages_Teams.setAutoFillBackground(False)
        self.menuManages_Teams.setStyleSheet("")
        self.menuManages_Teams.setObjectName("menuManages_Teams")
        MainWindow.setMenuBar(self.Manage_Team)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_team = QtWidgets.QAction(MainWindow)
        self.new_team.setObjectName("new_team")
        self.open_team = QtWidgets.QAction(MainWindow)
        self.open_team.setObjectName("open_team")
        self.save_team = QtWidgets.QAction(MainWindow)
        self.save_team.setObjectName("save_team")
        self.evaluate_team = QtWidgets.QAction(MainWindow)
        self.evaluate_team.setObjectName("evaluate_team")
        self.menuManages_Teams.addAction(self.new_team)
        self.menuManages_Teams.addAction(self.open_team)
        self.menuManages_Teams.addAction(self.save_team)
        self.menuManages_Teams.addAction(self.evaluate_team)
        self.Manage_Team.addAction(self.menuManages_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket"))
        self.label.setText(_translate("MainWindow", "Your Selections"))
        self.batsman.setPlainText(_translate("MainWindow", "Batsman (BAT) ##"))
        self.bowler.setPlainText(_translate("MainWindow", "Bowlers (BOW) ##"))
        self.allrounder.setPlainText(_translate("MainWindow", "Allrounder (AR) ##"))
        self.wicketkeeper.setPlainText(_translate("MainWindow", "WicketKeeper (WK) ##"))
        self.pointavailable.setPlainText(_translate("MainWindow", "Point Available: 1000"))
        self.pointused.setPlainText(_translate("MainWindow", "Point Used: 0000"))
        self.radio_bat.setText(_translate("MainWindow", "BAT"))
        self.radio_bow.setText(_translate("MainWindow", "BOW"))
        self.radio_ar.setText(_translate("MainWindow", "AR"))
        self.radio_wk.setText(_translate("MainWindow", "WK"))
        self.teamname.setText(_translate("MainWindow", "Team Name : "))
        self.menuManages_Teams.setTitle(_translate("MainWindow", "Manages Teams"))
        self.new_team.setText(_translate("MainWindow", "NEW Team"))
        self.open_team.setText(_translate("MainWindow", "OPEN Team"))
        self.save_team.setText(_translate("MainWindow", "SAVE Team"))
        self.evaluate_team.setText(_translate("MainWindow", "EVALUATE Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

